### ISSUE TITLE
Platform Mismatch Error on ARM64 (Rock Pi 4C Plus)

### ISSUE THREAD

**Issue by truetype74** [beans-are-gross/mdash#2]
Description:
I am trying to set up mdash using Docker on a Rock Pi 4C Plus running Debian (Linux rock-4c-plus 5.10.110-20-rockchip, aarch64). After following the installation steps, I encountered an error related to platform mismatch when running docker compose up -d.

Steps to Reproduce:

Created Docker volumes and network as instructed:

```
docker volume create mdash-root  
docker volume create mdash-php  
docker volume create mdash-caddyfile  
docker network create mdash --subnet 172.220.0.0/24  
Created a docker-compose.yml file with the following content:
```

```
name: mdash  
services:  
    mysql:  
        container_name: mdash-mysql  
        networks:  
            mdash:  
                ipv4_address: 172.220.0.5  
        environment:  
            - MYSQL_ROOT_HOST=%  
            - MYSQL_ROOT_PASSWORD=<your-database-password>  
        image: mysql  
        restart: unless-stopped  
    mdash:  
        container_name: mdash-installer  
        networks:  
            - mdash  
        volumes:  
            - mdash-root:/mdash/  
            - mdash-php:/var/www/  
            - mdash-caddyfile:/etc/caddy/  
        environment:  
            - DB_PASS=mypassword  
        image: beansaregross/mdash  
        restart: unless-stopped  
networks:  
    mdash:  
        external: true  
        name: mdash  
volumes:  
    mdash-root:  
        external: true  
        name: mdash-root  
    mdash-php:  
        external: true  
        name: mdash-php  
    mdash-caddyfile:  
        external: true  
        name: mdash-caddyfile  
```
Ran sudo docker compose up -d.

Expected Result:
The containers should start successfully, and mdash should be accessible.

Actual Result:
The following error occurred:

`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  `

System Information:

Device: Rock Pi 4C Plus

OS: Debian

Kernel: Linux rock-4c-plus 5.10.110-20-rockchip #e0ac49d1b SMP Tue Sep 26 08:20:36 UTC 2023 aarch64

Docker Version: (Docker version 28.0.1, build 068a01e)

Docker Compose Version: (Docker Compose version v2.33.1)
