### ISSUE TITLE
Problem with mdash-installer first one-shoot ru n

### ISSUE THREAD

**Issue by truetype74** [beans-are-gross/mdash#3]
**Problem Description.
I am trying to install mDash using Docker, but the process fails with an error `mysqli_sql_exception: No route to host` in line 149 of the `setup.php` file. The container fails to connect to the database.

**Commands Executed:**
``
bash
docker run -d --name mdash-installer --restart unless-stopped --network mdash \
-v mdash-root:/mdash/ -v mdash-php:/var/www/ -v mdash-caddyfile:/etc/caddy/ \
-e DB_PASS="mypassword" beansaregross/mdash:arm
``
mdash-installer logs
``
[Timestamp] PHP Fatal error: Uncaught mysqli_sql_exception: No route to host in /mdash-installer/mdash/setup.php:149
Stack trace:
#0 /mdash-installer/mdash/setup.php(149): mysqli_connect()
#1 {main}
  thrown in /mdash-installer/mdash/setup.php on line 149
``

im using :

Operating System:

OS: Debian

Kernel: Linux rock-4c-plus 5.10.110-20-rockchip

Architecture: aarch64

Thank you in advance for any help.

**Comment by beans-are-gross** [comment]
Is your mysql server running on the same network as the installer?

**Comment by truetype74** [comment]
> Is your mysql server running on the same network as the installer?

Yep its the docker installation made before with the docker compose, and after that launched the one-shoot run.

**Comment by beans-are-gross** [comment]
Sorry about that, here is the new docker compose, however, I dont think this will fix the issue as the "No route to host" is a network error.

If the new compose doesnt work, can you output the results of this command `docker container ls --network mdash`

```
name: mdash
services:
    mysql:
        container_name: mdash-mysql
        networks:
            mdash:
                ipv4_address: 172.220.0.5
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=<your-database-password>
        image: mysql
        restart: unless-stopped
    mdash-php:
        container_name: mdash-php
        networks:
            mdash:
                ipv4_address: 172.220.0.10
        ports:
            - 9000:9000
        volumes:
            - mdash-root:/mdash/
            - mdash-php:/var/www/
        image: beansaregross/mdash-php
    caddy:
        container_name: mdash-caddy
        networks:
            - mdash
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - mdash-root:/mdash/
            - mdash-php:/var/www/
            - mdash-caddyfile:/etc/caddy/
        image: caddy
networks:
    mdash:
        external: true
        name: mdash
volumes:
    mdash-root:
        external: true
        name: mdash-root
    mdash-php:
        external: true
        name: mdash-php
    mdash-caddyfile:
        external: true
        name: mdash-caddyfile

```

**Comment by truetype74** [comment]
> Sorry about that, here is the new docker compose, however, I dont think this will fix the issue as the "No route to host" is a network error.
> 
> If the new compose doesnt work, can you output the results of this command `docker container ls --network mdash`
> 
> ```
> name: mdash
> services:
>     mysql:
>         container_name: mdash-mysql
>         networks:
>             mdash:
>                 ipv4_address: 172.220.0.5
>         ports:
>             - 3306:3306
>         environment:
>             - MYSQL_ROOT_HOST=%
>             - MYSQL_ROOT_PASSWORD=<your-database-password>
>         image: mysql
>         restart: unless-stopped
>     mdash-php:
>         container_name: mdash-php
>         networks:
>             mdash:
>                 ipv4_address: 172.220.0.10
>         ports:
>             - 9000:9000
>         volumes:
>             - mdash-root:/mdash/
>             - mdash-php:/var/www/
>         image: beansaregross/mdash-php
>     caddy:
>         container_name: mdash-caddy
>         networks:
>             - mdash
>         ports:
>             - 80:80
>             - 443:443
>             - 8080:8080
>         volumes:
>             - mdash-root:/mdash/
>             - mdash-php:/var/www/
>             - mdash-caddyfile:/etc/caddy/
>         image: caddy
> networks:
>     mdash:
>         external: true
>         name: mdash
> volumes:
>     mdash-root:
>         external: true
>         name: mdash-root
>     mdash-php:
>         external: true
>         name: mdash-php
>     mdash-caddyfile:
>         external: true
>         name: mdash-caddyfile
> ```

thanks but as written in my configuration debian 10 and rock pi 4c plus on arm64 system i can't find a correct combination of images i tried first to compile the docker-compose as proposed and it didn't go because they were prepared for amd processor, then i tried one by one the images with the tags :arm and not even that then tried out of desperation :arm64 and :aarch but no luck.

**Comment by truetype74** [comment]
After numerous attempts and various manipulations on docker cli commands various prune of dirty containers and images hung and forcibly removed I managed to use this system to start the initial compose that I post now I wait if it comes out with the much coveted 143 

```
docker


name: mdash
services:
    mysql:
        container_name: mdash-mysql
        networks:
            mdash:
                ipv4_address: 172.220.0.5
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD="mypassword"
        image: mysql
        restart: unless-stopped
    mdash:
        container_name: mdash-installer
        networks:
            - mdash
        volumes:
            - mdash-root:/mdash/
            - mdash-php:/var/www/
            - mdash-caddyfile:/etc/caddy/
        environment:
            - DB_PASS=<your-database-password>
        image: beansaregross/mdash:arm
        restart: unless-stopped
networks:
    mdash:
        external: true
        name: mdash
volumes:
    mdash-root:
        external: true
        name: mdash-root
    mdash-php:
        external: true
        name: mdash-php
    mdash-caddyfile:
        external: true
        name: mdash-caddyfile
```
